Repository f-lab-edu/infrun, pull requests merged in 2023-09, with the labels that each got.

#41 [#9] 강의 리뷰 기능 구현
  src/main/java/com/flab/infrun/common/config/security/SecurityConfig.java
  src/main/java/com/flab/infrun/common/exception/ErrorCode.java
  src/main/java/com/flab/infrun/lecture/application/LectureCommandProcessor.java
  src/main/java/com/flab/infrun/lecture/application/LectureFacade.java
  src/main/java/com/flab/infrun/lecture/application/command/LectureReviewDeleteCommand.java
  src/main/java/com/flab/infrun/lecture/application/command/LectureReviewModifyCommand.java
  src/main/java/com/flab/infrun/lecture/application/command/LectureReviewRegisterCommand.java
  src/main/java/com/flab/infrun/lecture/domain/LectureDetail.java
  src/main/java/com/flab/infrun/lecture/domain/LectureReview.java
  src/main/java/com/flab/infrun/lecture/domain/exception/InvalidAuthorizationLectureReviewException.java
  src/main/java/com/flab/infrun/lecture/domain/exception/NotFoundLectureException.java
  src/main/java/com/flab/infrun/lecture/domain/exception/NotFoundLectureReviewException.java
  src/main/java/com/flab/infrun/lecture/domain/repository/LectureDetailRepository.java
  src/main/java/com/flab/infrun/lecture/domain/repository/LectureFileRepository.java
  src/main/java/com/flab/infrun/lecture/domain/repository/LectureRepository.java
  src/main/java/com/flab/infrun/lecture/domain/repository/LectureReviewRepository.java
  src/main/java/com/flab/infrun/lecture/infrastructure/config/LecturePersistenceConfig.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/LectureDetailRepositoryAdapter.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/LectureFileRepositoryAdapter.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/LectureRepositoryAdapter.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/LectureReviewRepositoryAdapter.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/jpa/LectureReviewJpaRepository.java
  src/main/java/com/flab/infrun/lecture/presentation/LectureController.java
  src/main/java/com/flab/infrun/lecture/presentation/request/LectureReviewDeleteRequest.java
  src/main/java/com/flab/infrun/lecture/presentation/request/LectureReviewModifyRequest.java
  src/main/java/com/flab/infrun/lecture/presentation/request/LectureReviewRegisterRequest.java
  src/main/resources/application.yaml
  src/test/java/com/flab/infrun/lecture/application/LectureCommandProcessorTest.java
  src/test/java/com/flab/infrun/lecture/application/LectureProcessorTest.java
  src/test/java/com/flab/infrun/lecture/application/LectureReviewProcessorTest.java
  src/test/java/com/flab/infrun/lecture/domain/StubLectureRepository.java
  src/test/java/com/flab/infrun/lecture/domain/StubLectureReviewRepository.java
  src/test/java/com/flab/infrun/member/domain/StubMemberRepository.java
Labels: enhancement

#57 hotfix(#56) -lecture repository package 오류 수정
  src/main/java/com/flab/infrun/lecture/application/LectureCommandProcessor.java
  src/main/java/com/flab/infrun/lecture/domain/LectureDetailRepository.java
  src/main/java/com/flab/infrun/lecture/domain/LectureFileRepository.java
  src/main/java/com/flab/infrun/lecture/domain/LectureRepository.java
  src/main/java/com/flab/infrun/lecture/domain/LectureReviewRepository.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/LectureDetailRepositoryAdapter.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/LectureFileRepositoryAdapter.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/LectureRepositoryAdapter.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/LectureReviewRepositoryAdapter.java
  src/test/java/com/flab/infrun/lecture/application/LectureCommandProcessorTest.java
  src/test/java/com/flab/infrun/lecture/application/LectureReviewProcessorTest.java
  src/test/java/com/flab/infrun/lecture/domain/StubLectureRepository.java
  src/test/java/com/flab/infrun/lecture/domain/StubLectureReviewRepository.java
  src/test/java/com/flab/infrun/member/domain/StubMemberRepository.java
  src/test/java/com/flab/infrun/utils/persistence/StubCouponRepository.java
  src/test/java/com/flab/infrun/utils/persistence/StubLectureRepository.java
  src/test/java/com/flab/infrun/utils/persistence/StubMemberRepository.java
Labels: hotfix

#54 [#51] Object Storage 활용한 강의 업로드
  build.gradle
  src/main/java/com/flab/infrun/cart/application/AddCartItemProcessor.java
  src/main/java/com/flab/infrun/cart/application/CartsReader.java
  src/main/java/com/flab/infrun/lecture/application/LectureCommandProcessor.java
  src/main/java/com/flab/infrun/lecture/application/LectureFacade.java
  src/main/java/com/flab/infrun/lecture/application/LectureQueryProcessor.java
  src/main/java/com/flab/infrun/lecture/application/command/LectureDetailCommand.java
  src/main/java/com/flab/infrun/lecture/application/command/LectureRegisterCommand.java
  src/main/java/com/flab/infrun/lecture/application/command/LectureReviewDeleteCommand.java
  src/main/java/com/flab/infrun/lecture/application/command/LectureReviewModifyCommand.java
  src/main/java/com/flab/infrun/lecture/application/command/LectureReviewRegisterCommand.java
  src/main/java/com/flab/infrun/lecture/application/command/PublishPreSignedUrlCommand.java
  src/main/java/com/flab/infrun/lecture/application/fileCommand/FileStorageUpload.java
  src/main/java/com/flab/infrun/lecture/application/fileCommand/StorageUpload.java
  src/main/java/com/flab/infrun/lecture/application/query/LectureSearchResult.java
  src/main/java/com/flab/infrun/lecture/application/result/LectureSearchResult.java
  src/main/java/com/flab/infrun/lecture/application/result/PreSignedUrlResult.java
  src/main/java/com/flab/infrun/lecture/domain/Lecture.java
  src/main/java/com/flab/infrun/lecture/domain/LectureDetail.java
  src/main/java/com/flab/infrun/lecture/domain/LectureFile.java
  src/main/java/com/flab/infrun/lecture/domain/LectureFileRepository.java
  src/main/java/com/flab/infrun/lecture/domain/LectureRepository.java
  src/main/java/com/flab/infrun/lecture/infrastructure/config/LecturePersistenceConfig.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/LectureFileRepositoryAdapter.java
  src/main/java/com/flab/infrun/lecture/infrastructure/persistence/jpa/LectureFileJpaRepository.java
  src/main/java/com/flab/infrun/lecture/infrastructure/storage/aws/SimpleStorageService.java
  src/main/java/com/flab/infrun/lecture/infrastructure/storage/aws/config/S3Config.java
  src/main/java/com/flab/infrun/lecture/presentation/LectureController.java
  src/main/java/com/flab/infrun/lecture/presentation/request/LectureDetailRequest.java
  src/main/java/com/flab/infrun/lecture/presentation/request/LectureRegisterRequest.java
  src/main/java/com/flab/infrun/lecture/presentation/request/LectureReviewDeleteRequest.java
  src/main/java/com/flab/infrun/lecture/presentation/request/LectureReviewModifyRequest.java
  src/main/java/com/flab/infrun/lecture/presentation/request/LectureReviewRegisterRequest.java
  src/main/java/com/flab/infrun/lecture/presentation/request/PreSingedUrlRequest.java
  src/main/java/com/flab/infrun/lecture/presentation/response/LectureQueryResponse.java
  src/main/java/com/flab/infrun/lecture/presentation/response/PreSignedUrlResponse.java
  src/main/resources/application.yaml
  src/test/java/com/flab/infrun/cart/application/CartsReaderTest.java
  src/test/java/com/flab/infrun/cart/application/FakeLectureRepository.java
  src/test/java/com/flab/infrun/lecture/application/LectureCommandProcessorTest.java
  src/test/java/com/flab/infrun/lecture/application/LectureReviewProcessorTest.java
  src/test/java/com/flab/infrun/lecture/domain/StubLectureRepository.java
  src/test/java/com/flab/infrun/lecture/infrastructure/persistence/LectureDetailRepositoryTest.java
  src/test/java/com/flab/infrun/lecture/infrastructure/persistence/LectureVideoFileRepositoryTest.java
  src/test/java/com/flab/infrun/lecture/presentation/LectureControllerApiTest.java
  src/test/java/com/flab/infrun/utils/persistence/StubLectureRepository.java
Labels: refactor

#61 hotfix(#60) -lecture repository package 오류 수정
  src/main/java/com/flab/infrun/cart/application/AddCartItemProcessor.java
  src/main/java/com/flab/infrun/cart/application/CartsReader.java
  src/main/java/com/flab/infrun/lecture/application/LectureCommandProcessor.java
  src/main/java/com/flab/infrun/lecture/domain/LectureRepository.java
  src/test/java/com/flab/infrun/cart/application/CartsReaderTest.java
  src/test/java/com/flab/infrun/cart/application/FakeLectureRepository.java
  src/test/java/com/flab/infrun/lecture/domain/StubLectureRepository.java
  src/test/java/com/flab/infrun/utils/persistence/StubLectureRepository.java
Labels: hotfix

#65 hotfix(#64) - Test Code 정상화
  src/test/java/com/flab/infrun/lecture/application/LectureReviewProcessorTest.java
  src/test/java/com/flab/infrun/lecture/presentation/LectureControllerApiTest.java
  src/test/resources/application.yaml
Labels: hotfix

#63 [#3] CI/CD 구성하기
  .github/workflows/CI-CD.yaml
  .github/workflows/Test.yaml
  .gitignore
  build.gradle
  docker/app.Dockerfile
  docker/database/config/mysql.cnf
  docker/database/db.Dockerfile
  docker/docker-compose.yaml
  src/main/java/com/flab/infrun/common/config/security/SecurityConfig.java
  src/main/java/com/flab/infrun/common/config/security/WebSecurityCustomizerByProfile.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/test/java/com/flab/infrun/member/presentation/MemberControllerTest.java
Labels: enhancement
